alexstudio/alexstudio/urls.py
#from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls"))
]

alexstudio/hello/urls.py
from django import views
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:name>", views.greet, name="greet"),
    path("alex", views.alex, name="alex")
]

alexstudio/newyear/urls.py
from django import views
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index")
]

alexstudio/tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

alexstudio/hello/models.py
from django.db import models

# Create your models here.

alexstudio/newyear/models.py
from django.db import models

# Create your models here.

alexstudio/tasks/models.py
from django.db import models

# Create your models here.

alexstudio/appt/views.py
from urllib import response
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return HttpResponse("Inside the app")


INSERT INTO flights (origin, destination, duration) VALUES ("New York", "London", 425);

alexstudio/hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, "hello/index.html")

def alex(request):
    return HttpResponse("I am in Alex func")

def greet(request, name):
    return render(request, "hello/greet.html", {
        "name" : name.capitalize()
    })

alexstudio/newyear/views.py
from django.shortcuts import render
import datetime

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": now.month == 1 and now.day == 1
    })

alexstudio/tasks/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django import forms
from django.urls import reverse

# Create your views here.
class NewTaskForm(forms.Form):
  task = forms.CharField(label="New Task")
  #priority = forms.IntegerField(label="Priority", min_value=1, max_value=5)

def index(request):
  if "tasks" not in request.session:
    request.session["tasks"] = []
  return render(request, "tasks/index.html", {
    "tasks": request.session["tasks"]
  })

def add(request):
  if request.method == "POST":
    form = NewTaskForm(request.POST)
    if form.is_valid():
      task = form.cleaned_data["task"]
      request.session["tasks"] += [task]
      return HttpResponseRedirect(reverse("tasks:index"))
    else:
      return render(request, "tasks/add.html",{
        "form": form
      })
      
  return render(request, "tasks/add.html", {
    "form": NewTaskForm()
  })

alexstudio/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>The text from file</title>
    </head>
    <body>
        <h1>Hello, {{ name }}!!!</h1>
    </body>
</html>

alexstudio/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>The text from file</title>
    </head>
    <body>
        <h1>I am super man!!!</h1>
        <table>
            <th>Hura</th>
            <td>1</td><td>2</td>
        </table>
    </body>
</html>

alexstudio/newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Is this new year</title>
        <link href="{% static 'newyear/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        {% if newyear %}
        <h1>YES</h1>
        {% else %}
        <h1>NO</h1>
        {% endif %}
    </body>
</html>

alexstudio/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
  <h1>Add tasks</h1>
  <form action="{% url 'tasks:add' %}" method="post">
    {% csrf_token %}
    <!--<input type="text" name="task">-->
    {{ form }}
    <input type="submit"> 
  </form>
  <a href="{% url 'tasks:index' %}">View Tasks</a>
{% endblock %}

alexstudio/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
<h1>Tasks</h1>
  <ul>
    {% for task in tasks %}
      <li>{{ task }}</li>
    {% empty %}
      <h2>No tasks.</h2>
    {% endfor %}
  </ul>
  <a href="{% url 'tasks:add' %}">Add new task</a>
{% endblock %}

alexstudio/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
 <title>Tasks</title>
</head>
<body>
  {% block body %}
  {% endblock %}
</body>
</html>